on:
  push:
    branches:
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:

  release:
    name: Publish and Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish Windows
      run: dotnet publish -p:PublishProfile=Win64 --no-restore
    - name: Publish Linux
      run: dotnet publish -p:PublishProfile=Linux64 --no-restore
      
    - name: Zip Setup
      uses: montudor/action-zip@v0.1.1
    - name: Zip Windows
      run: zip -qq -r sdklauncher_win64.zip .
      working-directory: ChaosInitiative.SDKLauncher/bin/Publish/win64
    - name: Zip Linux
      run: zip -qq -r sdklauncher_linux64.zip .
      working-directory: ChaosInitiative.SDKLauncher/bin/Publish/linux64

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        artifacts: "sdklauncher_win64.zip,sdklauncher_linux64.zip"
        tag: "RELEASE_TAG"
        draft: true
        prerelease: false
